### ISSUE TITLE
Map transitions

### ISSUE THREAD

**Issue by Nessiah** [Nessiah/Frogivera#3]
Preload adjacent maps, transition to them when interacting with the respective elements.
Transition types:
* Fading
* Sliding (zelda-like)

**Comment by BotsBotsBotsBots** [comment]
Would be nice for the fade to be really rough, like just jumping between 3 or 4 fade levels, instead of a smooth fade, to emulate those [tileset swap fades](http://bisqwit.iki.fi/cv2fin/dev/cv2_fade_multi5.gif) that gb games used. I presume an actual tileset swap fade would be too ridiculous to make.

**Comment by Nessiah** [comment]
Are those tileset swaps or just pallete swaps?
Tileset swaps **might** not be **too** hard (to be figured out in issue #1), except maybe for the making them part.

**Comment by BotsBotsBotsBots** [comment]
Yeah, i meant palette swaps. Doing tileset swaps might be a possible way to do it but I'd have to make like, three or four variations of each tileset that can have a fade happening, which seems like it might be a tad overkill..
Perhaps a rough fade using a multiply layer effect... Lemme make some Tests.

**Comment by BotsBotsBotsBots** [comment]
No, that looks like a regular fade, nevermind. Still, making it in four rough frames instead of a smooth fade does improve the effect so that's a start. I wonder if the tileset swap fade is worth the effort though..
